# Generated by Django 4.1.3 on 2022-11-21 10:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Yoshi')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='aktyorrasmi/', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Aktyor va rejissyor',
                'verbose_name_plural': 'Aktyorlar va rejissyorlar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Janr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Janr nomi')),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Janr',
                'verbose_name_plural': 'Janrlar',
            },
        ),
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('tagline', models.CharField(default='', max_length=200, verbose_name='Shiori')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('poster', models.ImageField(upload_to='kino/', verbose_name='Plakat rasm')),
                ('year', models.PositiveSmallIntegerField(default=2021, verbose_name='Ishlab chiqarilish sanasi')),
                ('country', models.CharField(max_length=100, verbose_name='Mamlakati')),
                ('world_premiers', models.DateField(default=datetime.date.today, verbose_name='Jahon primyerasi')),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('actors', models.ManyToManyField(related_name='Filimaktyori', to='movie.actyor', verbose_name='Aktyor')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.category', verbose_name='Kategoriya')),
                ('directors', models.ManyToManyField(related_name='FilimRahbari', to='movie.actyor', verbose_name='Rejissyor')),
                ('genres', models.ManyToManyField(to='movie.janr', verbose_name='Janiri')),
            ],
            options={
                'verbose_name': 'Kino',
                'verbose_name_plural': 'Kinolar',
            },
        ),
        migrations.CreateModel(
            name='ReytingYulduzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mashxur reyting',
                'verbose_name_plural': 'Mashxur reytinglar',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Reyting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retings', to='movie.kino', verbose_name='Kino')),
                ('star', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.reytingyulduzi', verbose_name='Yulduz')),
            ],
            options={
                'verbose_name': 'Reyting',
                'verbose_name_plural': 'Reytinlar',
            },
        ),
        migrations.CreateModel(
            name='KinoKadrlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('image', models.ImageField(upload_to='kadrrasmi/', verbose_name='Kadr_rasmlari')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.kino', verbose_name='Kino')),
            ],
            options={
                'verbose_name': 'Film kadiri',
                'verbose_name_plural': 'Film Kadrlari',
            },
        ),
    ]
